Added search input
pinax-network/golang-base pull request #85
Opened 2024-04-11 15:10 UTC by chamorin

2024-04-12 08:19 UTC, fschoell requested changes

2024-04-12 08:19 UTC, fschoell commented on validate/validator.go
> +	SearchPairRegex  = regexp.MustCompile(`^([a-zA-Z0-9_\-\.]+)(:([a-zA-Z0-9_\-\.]+))?$`)
the value part here is optional which is probably not intended (that regex matches a single word like `test`)?

2024-04-12 16:21 UTC, chamorin commented on validate/validator.go
> +	SearchPairRegex  = regexp.MustCompile(`^([a-zA-Z0-9_\-\.]+)(:([a-zA-Z0-9_\-\.]+))?$`)
Oh yes my bad, will fix

2024-04-15 10:19 UTC, fschoell approved these changes

2024-04-15 15:28 UTC, merged